# Generated by Django 3.0.8 on 2021-12-04 16:49

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrOlimpya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('biography', models.TextField(blank=True, max_length=5000, verbose_name='Biografía')),
                ('weight', models.CharField(max_length=50, verbose_name='Peso')),
                ('height', models.CharField(max_length=50, verbose_name='Altura')),
                ('age', models.CharField(max_length=50, verbose_name='Edad')),
                ('phrases', models.TextField(blank=True, max_length=5000, verbose_name='Frases Comunes')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
