# Generated by Django 3.0.8 on 2021-12-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mrolimpya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
