# Generated by Django 3.2.11 on 2022-02-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_raynhardtjwt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaynhardtJWT',
        ),
    ]
