# Generated by Django 3.2.11 on 2022-02-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_raynhardtjwt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raynhardtjwt',
            old_name='usuario',
            new_name='user',
        ),
    ]
