# Generated by Django 3.2.11 on 2022-02-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_usuario_raynhardtjwt_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MrOlimpya',
        ),
    ]
