# Generated by Django 3.2.11 on 2022-02-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_mrolimpya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaynhardtJWT',
        ),
    ]
